# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NextyWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NextyWallet
  platform :ios,'9.0'
  pod 'Firebase/Core','~> 5.11.0'
  pod 'Firebase/Messaging'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'NextyWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NextyWallet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NextyWallet-tvOS

  target 'NextyWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
